# Generated by Django 5.2.7 on 2025-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('General', 'General Physician'), ('Orthopedic', 'Orthopedic Surgeon'), ('Psychiatrist', 'Psychiatrist'), ('Ophthalmologist', 'Ophthalmologist'), ('ENT', 'Ear, Nose & Throat Specialist'), ('Gynecologist', 'Gynecologist'), ('Urologist', 'Urologist'), ('Oncologist', 'Oncologist'), ('Endocrinologist', 'Endocrinologist'), ('Nephrologist', 'Nephrologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Pulmonologist', 'Pulmonologist'), ('Rheumatologist', 'Rheumatologist')], max_length=50),
        ),
    ]
